version: '3.8'

services:
  restaurant_management_app:
    # Use the Docker image built from the Dockerfile in the current directory
    build: .
    # Set environment variables for the Django app container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      
    # Set the working directory to /app/restaurant_management inside the container
    working_dir: /app/restaurant_management
    # Expose port 8000 on the container and map it to port 8000 on the host
    ports:
      - "8000:8000"
    # Command to start the Django development server
    command: python manage.py runserver 0.0.0.0:8000
