# Generated by Django 4.2.2 on 2023-06-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_order_status_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.CharField(max_length=20),
        ),
    ]
