# Generated by Django 4.2.2 on 2023-06-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_order_items_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(through="app.OrderItem", to="app.item"),
        ),
    ]
