# Generated by Django 4.2.2 on 2023-07-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_order_items_order_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="item",
            new_name="item_id",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="order",
            new_name="order_id",
        ),
    ]
