# Generated by Django 4.2.2 on 2023-07-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_item_orderitem_item_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="order_id",
            new_name="order",
        ),
    ]
