var searchData=
[
  ['0001_5finitial_0',['0001_initial',['../namespaceapp_1_1migrations_1_10001__initial.html',1,'app.migrations.0001_initial'],['../namespaceauthentication_1_1migrations_1_10001__initial.html',1,'authentication.migrations.0001_initial']]],
  ['0002_5fcustomer_1',['0002_customer',['../namespaceapp_1_1migrations_1_10002__customer.html',1,'app::migrations']]],
  ['0003_5falter_5fcustomer_5fcreated_5fat_2',['0003_alter_customer_created_at',['../namespaceapp_1_1migrations_1_10003__alter__customer__created__at.html',1,'app::migrations']]],
  ['add_5for_5fupdate_5forder_5fitem_3',['add_or_update_order_item',['../namespaceapp_1_1views.html#a546104d3faee8be8cc604a503d33d61d',1,'app::views']]],
  ['address_4',['address',['../classapp_1_1models_1_1_customer.html#a360c3e112f9c241f01f0866b9cae1d60',1,'app::models::Customer']]],
  ['admin_5',['admin',['../namespaceapp_1_1admin.html',1,'app.admin'],['../namespaceauthentication_1_1admin.html',1,'authentication.admin']]],
  ['admin_2epy_6',['admin.py',['../authentication_2admin_8py.html',1,'(Global Namespace)'],['../app_2admin_8py.html',1,'(Global Namespace)']]],
  ['allowed_5fhosts_7',['ALLOWED_HOSTS',['../namespacerestaurant__management_1_1settings.html#a984eeba6646dac3ddf2ef5fcb89686ea',1,'restaurant_management::settings']]],
  ['app_8',['app',['../namespaceapp.html',1,'']]],
  ['appconfig_9',['AppConfig',['../classapp_1_1apps_1_1_app_config.html',1,'app::apps']]],
  ['application_10',['application',['../namespacerestaurant__management_1_1asgi.html#a4c00df34dc1b73f30ccae09f48829686',1,'restaurant_management.asgi.application'],['../namespacerestaurant__management_1_1wsgi.html#a42409ecdcb21e01dfff343080538a894',1,'restaurant_management.wsgi.application']]],
  ['apps_11',['apps',['../namespaceapp_1_1apps.html',1,'app.apps'],['../namespaceauthentication_1_1apps.html',1,'authentication.apps']]],
  ['apps_2epy_12',['apps.py',['../authentication_2apps_8py.html',1,'(Global Namespace)'],['../app_2apps_8py.html',1,'(Global Namespace)']]],
  ['asgi_2epy_13',['asgi.py',['../asgi_8py.html',1,'']]],
  ['auth_5fpassword_5fvalidators_14',['AUTH_PASSWORD_VALIDATORS',['../namespacerestaurant__management_1_1settings.html#a00bd7f0e05db2695ab5eadea94f07f5c',1,'restaurant_management::settings']]],
  ['auth_5fuser_5fmodel_15',['AUTH_USER_MODEL',['../namespacerestaurant__management_1_1settings.html#a17e2114213a9a7dc3dad95a3a75d9d55',1,'restaurant_management::settings']]],
  ['authenticated_5fclient_16',['authenticated_client',['../namespaceapp_1_1test__.html#aa91b9f6b9aed8ebbb4a2ca17a3391b08',1,'app::test_']]],
  ['authentication_17',['authentication',['../namespaceauthentication.html',1,'']]],
  ['authenticationconfig_18',['AuthenticationConfig',['../classauthentication_1_1apps_1_1_authentication_config.html',1,'authentication::apps']]],
  ['migrations_19',['migrations',['../namespaceapp_1_1migrations.html',1,'app.migrations'],['../namespaceauthentication_1_1migrations.html',1,'authentication.migrations']]],
  ['models_20',['models',['../namespaceapp_1_1models.html',1,'app.models'],['../namespaceauthentication_1_1models.html',1,'authentication.models']]],
  ['orders_5fserializers_21',['orders_serializers',['../namespaceapp_1_1serializers_1_1orders__serializers.html',1,'app::serializers']]],
  ['serializers_22',['serializers',['../namespaceapp_1_1serializers.html',1,'app.serializers'],['../namespaceapp_1_1serializers_1_1serializers.html',1,'app.serializers.serializers'],['../namespaceauthentication_1_1serializers.html',1,'authentication.serializers']]],
  ['test_5f_23',['test_',['../namespaceapp_1_1test__.html',1,'app']]],
  ['tests_24',['tests',['../namespaceauthentication_1_1tests.html',1,'authentication']]],
  ['urls_25',['urls',['../namespaceapp_1_1urls.html',1,'app.urls'],['../namespaceauthentication_1_1urls.html',1,'authentication.urls']]],
  ['views_26',['views',['../namespaceapp_1_1views.html',1,'app.views'],['../namespaceauthentication_1_1views.html',1,'authentication.views']]]
];
