name: Test Cases

on: [push] # Trigger the workflow on code push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest # You can also use other OS options like macOS or windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.17 # Use a supported Python version (e.g., 3.8, 3.9, or 3.10)

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Change to Django project directory
        working-directory: ./restaurant_management
        run: |
          # Optional: You can also list the project directory contents to ensure you're in the right place
          ls

      
      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: "restaurant_management.settings"
        working-directory: ./restaurant_management
        run: |
          pytest